### ISSUE TITLE
Is it possible to connect this UI to a dockerized version of wireguard?

### ISSUE THREAD

**Issue by matthiasbaldi** [EmbarkStudios/wg-ui#115]
**Is your feature request related to a problem? Please describe.**
When I saw that correct it is not possible to connect this UI to a dockerized version of wireguard.
https://github.com/orgs/linuxserver/packages/container/package/wireguard

Did I miss something or is this currently just not possible?

**Describe the solution you'd like**
Run wireguard and wireguard-ui as containers in parallel.

**Comment by adrum** [comment]
@matthiasbaldi I struggled getting this container working out of the box. I have a proof of concept of this exact implementation here: https://github.com/adrum/wireguard-ui

It combines the two containers into a single container. Rather than using wgctrl-go for controlling the wg0 interface, I modified this server code to generate the normal wireguard config files that linuxserver/wireguard is expecting. Best of both worlds.

**Comment by matthiasbaldi** [comment]
Well done.
May some more documentation would be required (at least for the Docker image) and an automatic build.
But else 👍

**Comment by adrum** [comment]
@matthiasbaldi I had some of this in progress, but I think it's close. I updated the readme with a basic compose file. 

https://hub.docker.com/r/adrum/wireguard-ui

**Comment by matthiasbaldi** [comment]
Perfect then let's close this issue in favor of your integration.
