### ISSUE TITLE
A newbie noobie setup guide

### ISSUE THREAD

**Issue by mhshakouri** [EmbarkStudios/wg-ui#39]
I would love a newbie noobie setup guide

**Comment by suom1** [comment]
I have now updated the documentation on how to build your own binary, and with that it should be really easy to get it running by yourself. 

After checking the documentation, do you still feel that there is something missing? In that case what would that be?

**Comment by dmgolembiowski** [comment]
Hi there! Newbie noob present! There's a temporary shortage of updated install instructions on the official WireGuard installation page for at least one of the operating systems listed -- and perhaps more, too. Since I know for certain that the Debian install process isn't up to snuff, is it possible to include a link to this source at [Linode](link: https://www.linode.com/docs/networking/vpn/set-up-wireguard-vpn-on-debian/)?
